name: Malu Workflow

on:
  push:
    branches: 
      - main
    schedule:
      - cron '0 * * * * '

jobs:
	build:
    runs-on: ubuntu-latest
		
    steps: 
	    - uses: actions/checkout@v2
	    - uses: ./action-a
      - run: echo "Olá :)"